source 'http://rubygems.org'

gem 'rails', '3.0.1'
#gem 'sqlite3-ruby', :require => 'sqlite3'
gem 'mysql2', '< 0.3'
gem 'dynamic_form'
gem 'devise'
gem 'omniauth'
#gem 'jquery-rails'
#gem 'ruby-debug'
#gem 'mongrel'
